### PR TITLE
[PET-000] Replacing CircleCI with Github Actions

### PR DESCRIPTION
**Pull request by pkramaric**
## Description
The goal of these actions is to replace the 2 CircleCI Orb jobs that are currently running. This includes the following:
Build-Docker: https://github.com/flybits/orbs/blob/main/src/backend/jobs/build-docker.yml
Push-Docker: https://github.com/flybits/orbs/blob/main/src/backend/jobs/push-docker.yml

Please compare the jobs in the orbs to the jobs I created to make sure I did not miss anything. There are obviously some tweaks but if you have questions it's better to ask.

### Checklist

  - [ ] PR title is clear and describes the work
  - [ ] Commit messages are self-explanatory and summarize the change

### Action

  - [ ] Tests are provided/updated for the new/existing action
  - [ ] The action maintainer in `CODEOWNERS` is updated
  - [ ] The `README.md` file for new/existing action is created/updated

### CODE REVIEW

**Comment by rileythomp** [comment]
Would it still be possible to filter out the renovate PRs from updating the dev image like in
https://github.com/flybits/orbs/blob/main/src/backend/jobs/push-docker.yml#L27-L43? Maybe in the `Inputs validation` step

**Comment by pkramaric** [comment]
@rileythomp we could but I was thinking of actually skipping all renovate branches in the repo workflows itself. Take a look at my PR here: https://github.com/flybits/labels/pull/419/files. In the pipeline-dev.yaml we exclude renovate PRs.
on:
  push:
    paths-ignore:
      - 'renovate/**'

**Comment by rileythomp** [comment]
Ah okay I see. Only concern with skipping them completely is that sometimes reno PRs break the build/test stage and require additional changes, so having them run those stages can be helpful. 
Also as an aside the name in each of those workflow files is `Pipeline - Dev`

**Comment by pkramaric** [comment]
hmm i suppose we can change the push docker step to exit if its from renovate, or we can have another another workflow for just renovate PRs. I will bring it up during backend sync when i go over this

**Review by ismaelvacco — APPROVED** [review]

**Comment by pkramaric** [comment]
@srdjanflybits @rileythomp bump bump as owners

**Review by rileythomp — APPROVED** [review]

**Review by srdjanflybits — APPROVED** [review]

**Pull request merged**
